=== HikkiChan/RiPS/Lab_7/schema.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.bsu.by" xmlns="http://www.bsu.by"
    elementFormDefault="qualified">

    <xs:simpleType name="species">
        <xs:restriction base="xs:string">
            <xs:enumeration value="LITE" />
            <xs:enumeration value="MAXIMUM" />
            <xs:enumeration value="SMART" />
        </xs:restriction>
    </xs:simpleType>
    <xs:element name="tariffs">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="tariff" maxOccurs="unbounded" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name" type="xs:string" />
                            <xs:element name="species" type="species" />
                            <xs:element name="subscriptionFee" type="xs:int" />
                            <xs:element name="costMinuteInNW" type="xs:int" />
                            <xs:element name="costMinuteInOtherNW" type="xs:int" />
                            <xs:element name="costSms" type="xs:int" />
                            <xs:element name="costInternet" type="xs:int" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== HikkiChan/RiPS/Lab_7/input.xml
<?xml version="1.0" encoding="UTF-8"?>
<tariffs
    xmlns="http://www.bsu.by"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.bsu.by schema.xsd">
    <tariff>
        <name>Tariff1</name>
        <species>LITE</species>
        <subscriptionFee>25</subscriptionFee>
        <costMinuteInNW>25</costMinuteInNW>
        <costMinuteInOtherNW>25</costMinuteInOtherNW>
        <costSms>25</costSms>
        <costInternet>25</costInternet>
    </tariff>
    <tariff>
        <name>Tariff2</name>
        <species>SMART</species>
        <subscriptionFee>50</subscriptionFee>
        <costMinuteInNW>15</costMinuteInNW>
        <costMinuteInOtherNW>15</costMinuteInOtherNW>
        <costSms>15</costSms>
        <costInternet>15</costInternet>
    </tariff>
    <tariff>
        <name>Tariff3</name>
        <species>MAXIMUM</species>
        <subscriptionFee>100</subscriptionFee>
        <costMinuteInNW>10</costMinuteInNW>
        <costMinuteInOtherNW>10</costMinuteInOtherNW>
        <costSms>10</costSms>
        <costInternet>10</costInternet>
    </tariff>
</tariffs>
